### ISSUE TITLE
Bold text in JComboBox with version 1.6.2

### ISSUE THREAD

**Issue by clausnagel** [JFormDesigner/FlatLaf#423] opened 2021-11-14 12:44 UTC
After updating to version 1.6.2, the text in my JComboBoxes is rendered in bold. I downloaded the [FlatLaf demo app](https://download.formdev.com/flatlaf/flatlaf-demo-latest.jar), and it shows the same behavior. It seems that editable combo boxes are not affected. I'm using Eclipse Temurin 11.0.12+7 on Windows 10 to run the app.

![image](https://user-images.githubusercontent.com/5517439/141681371-ee937700-84cf-41ec-bb1c-f727524d1ba0.png)

**Comment by DevCharly** [comment] 2021-11-14 13:40
Strange, don't have this effect on my main desktop PC (Windows 11), but on another PC (Windows 10).
The combobox text looks bold because it uses "grayscale" antialiasing. Otherwise "lcd" antialiasing is used.

This is caused by using a round rectangle for clipping. See commit 0b6df8be1c3fe3be0103a5f149afcbed065c41f8

**Comment by clausnagel** [comment] 2021-11-14 15:18
I am not using round components in my app. I tested the following:

- added `putClientProperty("JComponent.roundRect", true)` to a single combobox: text is still bold
- added `putClientProperty("JComponent.roundRect", false)` to a single combobox: text is not bold for this combobox anymore
- added `UIManager.put("Component.arc", 0)` at the startup of my app: text is not bold for all comboboxes

So, the last option does the trick for me. Just wonder why it's necessary.

**Comment by DevCharly** [comment] 2021-11-14 15:39
> I am not using round components in my app.

Comboboxes, spinners and buttons, etc. have (small) round corners by default.

> Just wonder why it's necessary.

Because the combobox has (small) round corners by default.
It is actually no problem with the small default corner radius because the border is painted over the background and "hides" the square corners of the background.

But if using larger corner radius (`Component.arc`) or `JComponent.roundRect = true`, then this happens before FlatLaf 1.6.2:

![image](https://user-images.githubusercontent.com/5604048/141687467-a80ad9a6-98e1-4462-95b1-95dc10f8cec7.png)

I'm working on a solution...

**Comment by DevCharly** [comment] 2021-11-14 22:31
Fixed in 1.6.3. Thanks for reporting 👍

**Closed by DevCharly** 2021-11-14 22:31 UTC
