### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Width (-1) and height (-1) cannot be <= 0

### ISSUE THREAD

**Issue by chauvanhieu** [JFormDesigner/FlatLaf#610] opened 2022-11-14 14:39 UTC
`Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Width (-1) and height (-1) cannot be <= 0
        at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
        at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
        at com.formdev.flatlaf.util.ScaledImageIcon.image2bufferedImage(ScaledImageIcon.java:175)
        at com.formdev.flatlaf.util.ScaledImageIcon.paintIcon(ScaledImageIcon.java:121)
        at java.desktop/javax.swing.plaf.basic.BasicLabelUI.paint(BasicLabelUI.java:191)
        at com.formdev.flatlaf.ui.FlatLabelUI.paint(FlatLabelUI.java:248)
        at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
        at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:852)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
        at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
        at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
        at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1656)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1631)
        at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1569)
        at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1336)
        at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5266)
        at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5076)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:878)
        at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:861)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:861)
        at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:834)
        at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
        at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)`

I got this error while building project while using flatlaf library. is there any way to solve this problem?

**Comment by DevCharly** [comment] 2022-11-14 14:51
The icon file is probably missing.

The exception is fixed in commit 1a456d5d684ae4addf0d9217308f1df933489327 for FlatLaf 3. With this commit, FlatLaf paints a red rectangle if the image file is missing.

**Comment by chauvanhieu** [comment] 2022-11-14 15:19
oh...no way to build projects with flatlaf. the only way is to wait for flatlaf 3.0

**Comment by DevCharly** [comment] 2022-11-14 15:24
Why wait for FlatLaf 3?

The problem is in your app. You can fix it.
The icon file is probably missing or you use a wrong name to load it.

**Comment by chauvanhieu** [comment] 2022-11-14 15:40
It's time to run on netbeans
![image](https://user-images.githubusercontent.com/95233436/201700195-88852aa1-0a9d-4318-badb-53d812aa439a.png)

this is the folder containing (jar) after "clean and build"
![image](https://user-images.githubusercontent.com/95233436/201701053-1aec40eb-afb7-41d0-97ab-ea99eff35a33.png)

and this is the time to run the jar
![image](https://user-images.githubusercontent.com/95233436/201701464-6e3111de-18b5-4c70-9d1c-3da75dc07636.png)

Everything is fine when running the application on Netbeans. but after "clean and build" got error of missing icon file. same error lines above. Okay I will check the files again. thanks Founder's Flatlaf ^^ I'll ask if I try and still can't fix it

**Comment by chauvanhieu** [comment] 2022-11-14 16:11
oh i know how. thankiu sir

**Closed** 2022-11-14 19:41 UTC
