### ISSUE TITLE
JCombobox problem (only when using two monitors)

### ISSUE THREAD

**Issue by MXandresMX** [JFormDesigner/FlatLaf#321] opened 2021-05-07 02:30 UTC
![1](https://user-images.githubusercontent.com/71142289/117389567-2c905400-aeb2-11eb-97bc-656f4a06ef53.png)

This happen in the last version. 
When interact with the JCombobox component.

Using 
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

**Comment by DevCharly** [comment] 2021-05-07 10:31
Hmm, can't reproduce...

It this a permanent problem?
Or does it repaint correctly if you e.g. click on another tab or resize the window?

This could be a problem with the animation Laf changing.
Please disable "Options > Animated Laf Change" (in FlatLaf Demo menu) and try again.

**Comment by DevCharly** [comment] 2021-05-07 10:38
Are there any exceptions if you launch the demo from command line with `java -jar flatlaf-demo-1.1.2.jar` ?
And does this occur always? Or somtimes?

**Comment by MXandresMX** [comment] 2021-05-07 14:44
> Hmm, can't reproduce...
> 
> It this a permanent problem?
> Or does it repaint correctly if you e.g. click on another tab or resize the window?
> 
> This could be a problem with the animation Laf changing.
> Please disable "Options > Animated Laf Change" (in FlatLaf Demo menu) and try again.

Yes its permanent. When i clic in JComboBox the gui do that in all other components. So i can see the problem is actived when clic in jcombobox. 
I disabled the "Animated Laf Change" and the problem persist.

**Comment by MXandresMX** [comment] 2021-05-07 14:49
![Animation](https://user-images.githubusercontent.com/71142289/117467732-92fc8d00-af19-11eb-90ec-64e9fcbfb2b2.gif)

**Comment by MXandresMX** [comment] 2021-05-07 15:00
Tested in Windows 10 Version 20H2(Compilation 19042.928)
-Java 8 last version same problem
-Java 11 last version same problem

Tested all version of Demo since 0.32RC to the last version 1.1.2 and problem persist.

**Comment by DevCharly** [comment] 2021-05-07 15:25
Many thanks for the screencasts and all the information.
This helps a lot to understand the problem.

Tried to reproduce with two monitors, but here it works (Windows 10 v2004).
Maybe it depends on the monitor layout.
Could you please run [FlatScreenInfo](https://github.com/JFormDesigner/FlatLaf/blob/main/flatlaf-testing/src/main/java/com/formdev/flatlaf/testing/FlatScreenInfo.java) and post the output.
(This is a single-file program that can be compiled/run without any other FlatLaf code or dependencies. Since Java 11, you can run this program from source with: `java FlatScreenInfo.java`)

BTW does the repaint problem go away when you close the combobox popup and resize the window (to force a repaint)?

I also wonder it you have the same problem if a non-FlatLaf look is active? E.g. Windows L&F.

**Comment by MXandresMX** [comment] 2021-05-07 16:07
> BTW does the repaint problem go away when you close the combobox popup and resize the window (to force a repaint)?
> 
> I also wonder it you have the same problem if a non-FlatLaf look is active? E.g. Windows L&F.

Scale factors:  100% / 100%
Java version:   1.8.0_281
Java vendor:    Oracle Corporation

ID:      \Display0 (main)
Size:    2560 x 1440 / 32 Bit / 240 Hz
Bounds:  2560 x 1440 / x 0 / y 0
Insets:  left 0 / right 0 / top 0 / bottom 40
Scale:   1.0

ID:      \Display1
Size:    3840 x 2160 / 32 Bit / 60 Hz
Bounds:  3840 x 2160 / x 2560 / y -223
Insets:  left 0 / right 0 / top 0 / bottom 40
Scale:   1.0


Other test.
If i change the FONT for example to Comic Sans the jcombobox work fine. If i increase the font size the jcombobox work fine, 
but if i clic in Restore Font then the problem return.

![Animation3](https://user-images.githubusercontent.com/71142289/117478106-5bdfa900-af24-11eb-96c4-6abcc46c2cf7.gif)

**Comment by DevCharly** [comment] 2021-05-13 12:57
Very very strange 😕 

Could you please try the FlatLaf Demo from this build:
https://github.com/JFormDesigner/FlatLaf/actions/runs/838906405

Download `FlatLaf-build-artifacts` (at the bottom of the above page), extract it and start
`FlatLaf-build-artifacts\flatlaf-demo\build\libs\flatlaf-demo-1.2-SNAPSHOT.jar`

**Comment by basix86** [comment] 2021-05-20 08:12
I suppose that is a problem of JDK.

With different monitors and some with 4k with scale factor > 100% sometimes there are the problem to recognize the correct screen position.

@MXandresMX Can you try to use this JDK ?
https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime

**Comment by MXandresMX** [comment] 2021-07-15 01:46
> I suppose that is a problem of JDK.
> 
> With different monitors and some with 4k with scale factor > 100% sometimes there are the problem to recognize the correct screen position.
> 
> @MXandresMX Can you try to use this JDK ?
> https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime
> 
> I suppose that you have this bug:
> https://youtrack.jetbrains.com/issue/JBR-153
> Not already solved in OpenJDK

Yes i tried with JetBrains and ocurr the same problem.
This is problem with the JDK in general. Because happen with Metal Look And Feel too.

My monitor is a game monitor with 240 Hz refresh rate.
I think this happend just with monitor with high refresh rate because i have a 4k monitor with 60hz refresh rate and don't happend that.

**Comment by DevCharly** [comment] 2021-08-02 16:50
Since this issue seems to be not related to FlatLaf, I'll close this issue for now.

**Closed by DevCharly** 2021-08-02 16:50 UTC
Labels: multi-screen

**Comment by jinsihou19** [comment] 2024-01-17 12:41
I have the same problem, my monitor is 4k with 60hz refresh rate. And not only JCombobox, other components will also trigger this phenomenon, it cannot be reproduced on other computers.
