### ISSUE TITLE
Vertical ScrollBar-Thumb sometimes vanish when quickly scrolling up and down

### ISSUE THREAD

**Issue by Bios-Marcel** [JFormDesigner/FlatLaf#171] opened 2020-09-07 15:15 UTC
Title says it all :P

I am on version 0.39 of flatlaf. According to the changelogs, there isn't a fix for this yet though.
I can't really narrow it down for now. Maybe I'll get around to look into this a bit deeper this week.

**EDIT**

I am currently unable to reproduce this.

**Comment by DevCharly** [comment] 2020-09-11 14:46
On what OS did this occur?
Used Java version?

**Comment by Bios-Marcel** [comment] 2020-09-11 14:55
Windows 10, Java 8 (OpenJDK 252 x64), Flatlaf 0.39 and I was using the `Flat Light` theme.

**Comment by DevCharly** [comment] 2020-11-16 15:20
Closing because not reproducible. Please reopen if it happens again.

**Closed by DevCharly** 2020-11-16 15:20 UTC
