### ISSUE TITLE
rounded border/corners for all input fields

### ISSUE THREAD

**Issue by rjahn** [JFormDesigner/FlatLaf#655] opened 2023-03-21 20:37 UTC
The borders of comboboxes are rounded, textfields are not rounded.
If you want the same border for all input fields, I guess it's not possible right now?

It's possible to set:

TextComponent.arc = 5

works for text fields.

But JTextArea which is used inside a JScrollpane, doesn't support rounded border?
If you set:

ScrollPane.border = com.formdev.flatlaf.ui.FlatTextBorder

the border is rounded, but the text area/viewport background is a rectangle without rounded corners.

So, is it possible to define all input fields (not table, tree or other components), only input fields - with rounded corners?

**Comment by DevCharly** [comment] 2023-08-13 23:09
There is now a draft PR for rounded scrollpanes. See PR #713.

**Comment by DevCharly** [comment] 2023-08-13 23:12
closing because duplicate of #594

**Closed by DevCharly** 2023-08-13 23:12 UTC

**Comment by DevCharly** [comment] 2023-12-21 17:10
implemented in latest `3.3-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots
