### ISSUE TITLE
Rendering artifacts on native decorated windows on HiDPI

### ISSUE THREAD

**Issue by joshmillikanqoppa** [JFormDesigner/FlatLaf#477] opened 2022-02-10 20:23 UTC
With native window decorations on Windows 10/11 using Java 11+ and a HiDPI monitor, we are getting rendering artifacts across the entire window when dragging a window back into the screen bounds.

Attached is the demo screenshot that has been dragged off screen to the south and then back into the screen bounds. Similar artifacts appear dragging east/west but with vertical lines
![flatlaf_native_window_hidpi](https://user-images.githubusercontent.com/74264518/153490378-a94e1bf8-892f-422d-8982-7ad3db5fdebd.png)
.

**Comment by DevCharly** [comment] 2022-02-16 22:11
Strange. Can't reproduced it...

And do you also get rendering artifacts if you disable FlatLaf window decorations?
(menu "Options > Window decorations" in demo)

**Comment by Wisser** [comment] 2022-02-16 23:29
I can reproduce this on Windows 11, scaling 175%. The artifacts disappear when FlatLaf window decorations is disabled.

**Comment by DevCharly** [comment] 2022-02-17 12:32
Thanks, can now reproduce it on another computer with Windows 10 at 200% scaling...

**Comment by joshmillikanqoppa** [comment] 2022-02-17 14:19
Yes, I cannot see the same line artifacts when native decorations are disabled. We were using both 175% and 200% on different testing machines.

**Comment by joshmillikanqoppa** [comment] 2022-02-17 14:27
Using a different background color across the entire content pane makes the lines much more visible. Appears to be a clipping/repaint issue with the root pane, maybe?

`import java.awt.Color;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;

import com.formdev.flatlaf.FlatDarkLaf;

public class SimpleFrame {

	public static void main(String[] args) {
		try	{
			UIManager.setLookAndFeel(new FlatDarkLaf());
		}
		catch (UnsupportedLookAndFeelException e) {
			e.printStackTrace();
		}
		
		SwingUtilities.invokeLater(() -> initGUI());
	}

	private static void initGUI() {
		JFrame frame  = new JFrame("Native Decoration Lines");
		frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		frame.setSize(800, 600);
		frame.setLocationRelativeTo(null);
		frame.getContentPane().setBackground(Color.red);
		frame.setVisible(true);
	}
}`

**Comment by DevCharly** [comment] 2022-02-18 21:55
Fixed in main branch.
Please try latest snapshot: https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by joshmillikanqoppa** [comment] 2022-02-22 20:03
The latest snapshot resolves the issue. Thank you.

**Closed** 2022-02-24 22:25 UTC
