### ISSUE TITLE
Table grid not painted for checkbox 

### ISSUE THREAD

**Issue by voidpointergonebad** [JFormDesigner/FlatLaf#311] opened 2021-04-20 16:09 UTC
flatlaf-1.1.2.jar

Bottom dialog without `FlatLightLaf.install();`

![flatlaf](https://user-images.githubusercontent.com/82895788/115428999-428bec80-a203-11eb-9cba-79d0091694a9.png)

```
package com.example;

import com.formdev.flatlaf.FlatLightLaf;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public final class Test extends JFrame {
  private static final long serialVersionUID = 1L;

  static final String[] COLUMNS = new String[] { "string", "boolean", "string" };
  static final Object[][] DATA = new Object[][] { { "aaa", false, "bbb" }, { "ccc", true, "ddd" }, { "eee", false, "fff" } };
  static final Class<?>[] COLUMN_CLASS = new Class<?>[] { String.class, Boolean.class, String.class };
  static final DefaultTableModel model = new DefaultTableModel(DATA, COLUMNS) {
    @Override
    public boolean isCellEditable(int row, int column) { return false; }
    @Override
    public Class<?> getColumnClass(int columnIndex) { return COLUMN_CLASS[columnIndex]; }
  };

  public Test() {
    final JTable table = new JTable(model);
    table.setShowGrid(true);
    table.setGridColor(Color.LIGHT_GRAY);
    add(new JScrollPane(table));
    setTitle("Test");
    setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    pack();
    setVisible(true);
  }

  public static void main(String[] args) {
    try {
      FlatLightLaf.install();
      SwingUtilities.invokeLater(new Runnable() {
        @Override
        public void run() { new Test(); }
      });
    } catch(final Exception e) {}
  }
}
```

**Comment by DevCharly** [comment] 2021-04-20 21:22
The problem is that the background of the checkbox is filled and paints over the grid lines
because the intercell spacing is `0, 0` in FlatLaf. Other Lafs use intercell spacing `1, 1`.

To workaround this, change intercell spacing to `1, 1`:
~~~java
table.setIntercellSpacing( new Dimension( 1, 1 ) );
~~~

![image](https://user-images.githubusercontent.com/5604048/115464932-1afe4980-a22e-11eb-95ad-3a07ca124c75.png)

Intercell spacing is zero in FlatLaf because grid lines are hidden by default in FlatLaf.

Intercell spacing affects selection painting:

![image](https://user-images.githubusercontent.com/5604048/115465190-7f210d80-a22e-11eb-8041-43f61bd15e24.png)

With zero intercell spacing:

![image](https://user-images.githubusercontent.com/5604048/115465195-82b49480-a22e-11eb-87a3-0f2efcb81f6d.png)


I work on a solution for the checkboxes that will work also with zero intercell spacing.

**Comment by voidpointergonebad** [comment] 2021-04-21 13:30
The workaround solves the immediate issue - thanks!

**Comment by DevCharly** [comment] 2021-04-24 09:59
Fixed in main branch. Now works also with zero intercell spacing.

**Closed by DevCharly** 2021-04-24 09:59 UTC
