### ISSUE TITLE
Exception Access Violation causing jvm crash after updating flatlaf version to 3.1(3.1.1)

### ISSUE THREAD

**Issue by liucunjie** [JFormDesigner/FlatLaf#673] opened 2023-04-30 12:48 UTC
Our program works fine on flatlaf v3.0, But jvm crash occurred after updating to 3.1 or 3.1.1.  I can't pinpoint the problem.  Any ideas are appreciated.
OS：windows 10
JVM: 1.8
[hs_err_pid12916.log](https://github.com/JFormDesigner/FlatLaf/files/11361334/hs_err_pid12916.log)

**Comment by DevCharly** [comment] 2023-05-02 16:11
Strange that it works with FlatLaf 3.0 but crashes with 3.1 because there is actually nearly no changes in native code regarding window decorations from 3.0 to 3.1. Only added new native methods. See commit https://github.com/JFormDesigner/FlatLaf/commit/07ad467c73c5593106507f7c6ac7b7df57877a65#diff-0393d6d30e320a47e5a348543e9382b73ddee2bfa56889beb3c9d4c88a3be8fd

And the used JRE and PC are the same in both cases?

Does it work with Java 11 or any other newer Java version?

**Comment by liucunjie** [comment] 2023-05-03 08:39
Thank you for giving suggestion. Thanks a lot :)
It worked after upgrading jre 8 to 11

Yes, all the test on the same JRE and PC.

**Comment by DevCharly** [comment] 2023-07-01 16:13
Finally was able to reproduce the crash 😄 

Occurs under following conditions:

- on Windows 10/11
- and application runs in Java 8 (but older than 8u321)
- and newer Java version (e.g. 11) is installed and added to `PATH` environment variable
- and using class SystemInfo before AWT initialization

The problem is that `awt.dll` from Java 11+ is loaded, via PATH variable, into Java 8, which causes the crash.

This can be seen in your log where `awt.dll` is loaded from Eclipse JRE 17 and from Java 8:

![image](https://github.com/JFormDesigner/FlatLaf/assets/5604048/398f8ec6-ce92-4b23-9a36-c266f867fc7e)

Here is the `PATH` from your log:

![image](https://github.com/JFormDesigner/FlatLaf/assets/5604048/7e1692fd-5e6d-4b58-b139-34794206fb70)

**Comment by DevCharly** [comment] 2023-07-01 16:44
fixed in latest `3.2-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

**Closed by DevCharly** 2023-07-01 16:44 UTC
