### ISSUE TITLE
Question about combobox style

### ISSUE THREAD

**Issue by martinm1000** [JFormDesigner/FlatLaf#227] opened 2020-12-16 19:27 UTC
Hi !

I can't find the UI default that makes non-editable combobox selected item in bold.
How can I control this ? I would like the selected non-editable item not to be bolder.

![image](https://user-images.githubusercontent.com/3790866/102396356-56e88000-3faa-11eb-9d45-a8e3e176a31f.png)

I have jcombobox items with html+bold, and the selected entry seems to have its non-bold text more bold that it should.

Old screenshot before using FlatLAF:
![image](https://user-images.githubusercontent.com/3790866/102396580-a2029300-3faa-11eb-9eca-c661f89b0ad8.png)

Now:
![image](https://user-images.githubusercontent.com/3790866/102396609-ab8bfb00-3faa-11eb-91b3-80e7f72f1133.png)

**Comment by DevCharly** [comment] 2020-12-16 20:09
> I can't find the UI default that makes non-editable combobox selected item in bold.

Hmm, I'm not aware of such an option. The text should be not bold.

![image](https://user-images.githubusercontent.com/5604048/102399768-591a0100-3fe1-11eb-8d03-d688d6676dae.png)

Also can not reproduce the "bolder" HTML text:

![image](https://user-images.githubusercontent.com/5604048/102400834-ba8e9f80-3fe2-11eb-978c-37e42d05b6b2.png)


Can you give me some details about your machine? Windows? Java version?

Looks like a problem with the combobox font.
The first screen shot is from the FlatLaf demo, right?
In the demo press `Ctrl+Shift+Alt+X`, which enables the FlatLaf [UI Inspector](https://github.com/JFormDesigner/FlatLaf/tree/master/flatlaf-extras#ui-inspector). 
Then move the mouse over the combobox and check whether the font in the tooltip is equal to other component types:

![image](https://user-images.githubusercontent.com/5604048/102400166-d0e82b80-3fe1-11eb-9bbc-b2a0777ab662.png)

**Comment by martinm1000** [comment] 2020-12-16 20:13
I'm currently connecting through RDP, I might need to adjust the quality settings here. But since I see correctly the difference with the combo choices...

This is on Windows 10, Java 15.0.1.
And yes, the 1st screenshot is your demo for the 0.45

![image](https://user-images.githubusercontent.com/3790866/102401233-fc065700-3fb0-11eb-85e1-1b1ee803494d.png)

**Comment by martinm1000** [comment] 2020-12-16 20:21
Oh wow, I'm sorry. It seems to be an artifact of my RDP connection at work (damn covid). With better quality settings, I don't see a difference anymore. I just don't understand why I was seeing bold **only** on non editable comboboxes... !

now:

![image](https://user-images.githubusercontent.com/3790866/102402026-3290a180-3fb2-11eb-89ce-09507fd68bf7.png)

It seems windows render differently under RDP, as I can still see the 'bold' in my earlier screenshot. Right ?

**Comment by martinm1000** [comment] 2020-12-16 20:38
I've dialed down my quality settings and I don't think I'm crazy:

The top one is ok and was my earlier run of the demo with high quality RDP settings.
I've superimposed another run of the demo (executed after changing to less quality).
The top one still looks ok, but the newly ran java seems to be affected.

![image](https://user-images.githubusercontent.com/3790866/102403421-3c1b0900-3fb4-11eb-9158-2c785fb24141.png)

I guess we could close this issue, as it is not a real problem under normal circumstances.

**Comment by DevCharly** [comment] 2020-12-16 20:43
It seems when using lower quality RDP, that anti-aliasing is disabled, except for non-editable comboboxes, which seem to use gray-scale anti-aliasing (from your first screenshot at 400%):

![image](https://user-images.githubusercontent.com/5604048/102403449-90d77780-3fe6-11eb-9519-c81845b99c84.png)

For higher quality RDP, default LCD anti-aliasing is used (from your first screenshot at 600%):

![image](https://user-images.githubusercontent.com/5604048/102403534-b2d0fa00-3fe6-11eb-897d-a80ccf920f85.png)

So the remaining question is why do FlatLaf non-editable comboboxes use gray-scale anti-aliasing for lower quality RDP?

**Comment by martinm1000** [comment] 2020-12-16 20:45
Maybe its not even FlatLaf related ? it's a bizarre one !

**Comment by martinm1000** [comment] 2020-12-16 20:57
Its not just the combo boxes:

![image](https://user-images.githubusercontent.com/3790866/102405194-c49aa900-3fb6-11eb-9553-053154b7766b.png)

Left=Demo session that was ran under high quality RDP + (32bits color)
Right=Demo session ran under GOOD quality + (24bits colors)

The multi-line tooltip seems to have the issue.

But this one is bizarre:
![image](https://user-images.githubusercontent.com/3790866/102405599-6a4e1800-3fb7-11eb-93b3-2dd8c3691685.png)

**Comment by DevCharly** [comment] 2020-12-16 21:26
Can now reproduce the problem on my Windows desktop when disabling AA via command line option `-Dawt.useSystemAAFontSettings=off`. Other Lafs like Windows, Nimbus, ... do not have this issue.

**Comment by DevCharly** [comment] 2020-12-18 15:57
Fixed in master branch. Thanks for reporting.

**Closed by DevCharly** 2020-12-18 15:57 UTC

**Comment by martinm1000** [comment] 2020-12-18 16:40
Oh nice ! thank you !
