### ISSUE TITLE
GUI breaks when the size is changed to the minimum

### ISSUE THREAD

**Issue by Kokecena** [JFormDesigner/FlatLaf#767] opened 2023-11-24 08:10 UTC
As the title says the GUI starts to break, it is fixed when it is maximized but if you do the same thing again it happens again, I thought it was something in my application, but it also happens in the demo application, this does not happen with the base look and feel
My application:

https://github.com/JFormDesigner/FlatLaf/assets/75457600/f5580b45-e5c8-417a-9e97-4adda7180bbf

In the demo application:

https://github.com/JFormDesigner/FlatLaf/assets/75457600/8704ee15-5fb2-4838-aee8-e3c5f8b75782

Maybe this has nothing to do with it, or maybe it does, but I don't know if the error is reported in the jdk bug system, when there is an application that overlays the java application the same effect begins to happen, I made sure not to have the MSI Afterburner or another application that overlaps.

I'm on Windows 11
Java version 17.0.6, BellSoft.

**Comment by DevCharly** [comment] 2023-11-25 16:50
Thanks for reporting and for the videos.

Looks similar to: https://github.com/JFormDesigner/FlatLaf/issues/700#issuecomment-1642487073

Was not able to reproduce it by manually resizing window to minimum size, but invoking `frame.setSize(0,0)` and manually increasing window size shows this effect each time.

Turns out that invoking following line from `FlatRootLayout.invalidateLayout()` causes the problem:

https://github.com/JFormDesigner/FlatLaf/blob/ec7673790c97f611fe73a903e8520fadb6f6c7ad/flatlaf-core/src/main/java/com/formdev/flatlaf/ui/FlatTitlePane.java#L598

Very strange that a simple repaint has this effect. 😕

**Comment by DevCharly** [comment] 2023-11-25 17:24
fixed in latest `3.3-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

Please try it out.

**Closed by DevCharly** 2023-11-25 17:24 UTC
