### ISSUE TITLE
NPE in version 2.5 on Windows

### ISSUE THREAD

**Issue by ptorngren** [JFormDesigner/FlatLaf#600] opened 2022-10-14 10:46 UTC
After upgrading to FlatLaf 2.5, we get a `NullPointerException` when launching on Windows 10 and 11 (runs OK on macOS, and also on Windows in version 2.4).

Error is stable (happens every time during startup), but it is hard to pinpoint the cause and create a simple test class.

Stacktrace:
`java.lang.NullPointerException: Cannot read field "preferred" because "this.xTotal" is null
   at java.desktop/javax.swing.BoxLayout.preferredLayoutSize(BoxLayout.java:294)
   at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
   at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
   at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1727)
   at java.desktop/java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
   at java.desktop/java.awt.Container.preferredSize(Container.java:1826)
   at java.desktop/java.awt.Container.getPreferredSize(Container.java:1810)
   at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1727)
   at com.formdev.flatlaf.ui.FlatRootPaneUI$FlatRootLayout.layoutContainer(FlatRootPaneUI.java:444)
   at java.desktop/java.awt.Container.layout(Container.java:1541)
   at java.desktop/java.awt.Container.doLayout(Container.java:1530)
   at java.desktop/java.awt.Container.validateTree(Container.java:1725)
   at java.desktop/java.awt.Container.validateTree(Container.java:1734)
   at java.desktop/java.awt.Container.validate(Container.java:1660)
   at java.desktop/java.awt.Container.validateUnconditionally(Container.java:1697)
   at java.desktop/java.awt.Window.show(Window.java:1055)
   at java.desktop/java.awt.Component.show(Component.java:1728)
   at java.desktop/java.awt.Component.setVisible(Component.java:1675)
   at java.desktop/java.awt.Window.setVisible(Window.java:1036)`

**Comment by DevCharly** [comment] 2022-10-16 08:34
Not sure what change in 2.5 causes the issue. I'll have a look...

Could be a threading issue. 
Do you invoke `Window.setVisible()` on the **main** thread?
Or on the AWT thread?

Make sure to use `SwingUtilities.invokeLater()`

Recommended way:

~~~java
public static void main( String[] args ) {
    SwingUtilities.invokeLater( () -> {
        FlatLightLaf.setup();
        JFrame frame = ...
        ...
        frame.setVisible(true);
    } );
}
~~~

**Comment by ptorngren** [comment] 2022-10-16 19:05
We launch using `SwingUtilities.invokeLater()`, it's running on the AWT thread.

**Comment by DevCharly** [comment] 2022-10-17 15:22
Found the problem, which was caused by a NPE in `FlatMenuItemRenderer.getTopLevelFont()` when using `JideMenu`.

Fixed in latest `2.6-SNAPSHOT`: https://github.com/JFormDesigner/FlatLaf#snapshots

Please give it a try.
If it fixes the issue in your app, I'll release FlatLaf 2.6 in a few days.

**Comment by ptorngren** [comment] 2022-10-17 17:14
Yes, works fine!

**Comment by DevCharly** [comment] 2022-10-18 09:33
Great.

FlatLaf 2.6 is now available 😄

**Closed by DevCharly** 2022-10-18 09:33 UTC
