### ISSUE TITLE
Rhino debugger tree tables don't render correctly

### ISSUE THREAD

**Issue by markscottwright** [JFormDesigner/FlatLaf#120] opened 2020-07-02 17:32 UTC
This of course could be Rhino's fault - they have a heavily customized Table called JTreeTable.  But the following code demonstrates the issue.  Run it and then try expanding the "tree" in the lower left panel.  It works unless you scroll down, then it doesn't seem to overwrite the entries.

(Otherwise, this look-and-feel looks *amazing* when debugging JavaScript!)

```java
import org.mozilla.javascript.ContextFactory;
import org.mozilla.javascript.ImporterTopLevel;

import com.formdev.flatlaf.FlatLightLaf;

public class Main {
    public static void main(String[] args) throws Exception {

        FlatLightLaf.install();
        ContextFactory factory = new ContextFactory();
        var dbg = org.mozilla.javascript.tools.debugger.Main
                .mainEmbedded("A Sample Test");
        dbg.attachTo(factory);

        var context = factory.enterContext();
        var scope = new ImporterTopLevel(context);
        dbg.setBreakOnEnter(true);
        dbg.setVisible(true);
        dbg.setExitAction(() -> {
            // close the debug window
            dbg.dispose();
        });

        context.evaluateString(scope,
                "importPackage(javax.swing);"
                        + "\nJOptionPane.showMessageDialog(null, 'Hello');\n",
                "A Sample Test", 1, null);
    }
}
```

Using these dependencies:

```xml
 <dependencies>
  <dependency>
   <groupId>com.formdev</groupId>
   <artifactId>flatlaf</artifactId>
   <version>0.37</version>
  </dependency>
  <dependency>
   <groupId>org.mozilla</groupId>
   <artifactId>rhino</artifactId>
   <version>1.7.12</version>
  </dependency>
 </dependencies>
```

**Comment by markscottwright** [comment] 2020-07-02 17:35
(Forgot to mention above, but System and Cross Platform L&Fs both behave as expected)

**Comment by DevCharly** [comment] 2020-07-03 13:35
Year, I see a problem in the tree, but I'm not sure whether it is the same problem that you have.

The problem is that the tree used to render first column has a different row height than the table.
In Windows L&F or Metal L&F both row heights are 16 (the default) and it works.

If running with FlatLaf in Java 8 with 150% scaling, the table row height is 30 and the tree row height still 16, which results in this:

![grafik](https://user-images.githubusercontent.com/5604048/86465901-dce17900-bd32-11ea-8f8a-2b5149770fd7.png)

In unscaled FlatLaf the table row height is 20 and the tree row height 16, which looks better, but not perfect:

![grafik](https://user-images.githubusercontent.com/5604048/86472610-b1b15680-bd3f-11ea-85e4-1e59ce21a2d1.png)

Expanding nodes by clicking on the leading arrow does not work correctly because the tree row height is too small and therefore a wrong row is calculated for the mouse click location
E.g. clicking on arrow in row 10 expands row 12.

I'm currently testing a fix for rhino. Will submit a PR soon.

Also have to fix the gray selection background in first row. This should be blue...

BTW did you see NPEs in output? I have a `NullPointerException` in `VariableModel.getValueAt()` when expanding `CallSite`:
~~~
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at org.mozilla.javascript.tools.debugger.VariableModel.getValueAt(SwingGui.java:2743)
	at org.mozilla.javascript.tools.debugger.treetable.TreeTableModelAdapter.getValueAt(TreeTableModelAdapter.java:125)
	at javax.swing.JTable.getValueAt(JTable.java:2720)
	at javax.swing.JTable.prepareRenderer(JTable.java:5712)
	at javax.swing.plaf.basic.BasicTableUI.paintCell(BasicTableUI.java:2114)
	at javax.swing.plaf.basic.BasicTableUI.paintCells(BasicTableUI.java:2016)
	at javax.swing.plaf.basic.BasicTableUI.paint(BasicTableUI.java:1812)
	at javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at javax.swing.JComponent.paintComponent(JComponent.java:780)
	at javax.swing.JComponent.paint(JComponent.java:1056)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
~~~

**Comment by DevCharly** [comment] 2020-07-04 13:49
Have created two PR at rhino to fix this:
- https://github.com/mozilla/rhino/pull/741
- https://github.com/mozilla/rhino/pull/739

**Comment by DevCharly** [comment] 2020-07-06 17:51
The two rhino PRs have been merged today.

**Closed** 2020-07-10 17:43 UTC
