### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by dinix2008** [JFormDesigner/FlatLaf#275] opened 2021-03-22 13:09 UTC
Hello, @DevCharly. 

I tried NetBeans RCP 12.3 + FlatLaf 1.1 today. I get an error when launching my application
```
java.lang.NullPointerException
	at com.formdev.flatlaf.ui.FlatTitlePane.findHorizontalGlue(FlatTitlePane.java:463)
	at com.formdev.flatlaf.ui.FlatTitlePane.updateNativeTitleBarHeightAndHitTestSpots(FlatTitlePane.java:715)
	at com.formdev.flatlaf.ui.FlatTitlePane.lambda$updateNativeTitleBarHeightAndHitTestSpotsLater$5(FlatTitlePane.java:675)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
```

**Comment by DevCharly** [comment] 2021-03-22 18:00
Thanks for reporting. Was not able to reproduce this. Seems to occur only under very special conditions...

Anyway, should be fixed in main branch.

Please try the latest `1.2-SNAPSHOT` and let me know whether it now works:
https://github.com/JFormDesigner/FlatLaf#snapshots

**Comment by dinix2008** [comment] 2021-03-23 06:33
Hello, @DevCharly, bug fixed :-) Thanx

**Closed** 2021-03-23 20:43 UTC
