### ISSUE TITLE
BasicJideTabbedPaneUI throws an error when using with flatlaf-jide-oss

### ISSUE THREAD

**Issue by lgvr123** [JFormDesigner/FlatLaf#230] opened 2020-12-29 22:56 UTC
Making a new ```JideTabbedPane``` throws an NullPointerException at the initialisation of the UI component when ```flatlaf-jide-oss```. There is no error when ```flatlaf-jide-oss``` is not loaded.

Basic code to reproduce the error:
```
package debug.jideflat;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.jidesoft.swing.JideTabbedPane;
import javax.swing.UIManager;

public class MainDialog extends javax.swing.JDialog {

    /** Creates new form MainDialog */
    public MainDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    @SuppressWarnings("unchecked")
    private void initComponents() {

        tabMain = new com.jidesoft.swing.JideTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabMain, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Forcing the default shape to something else than SHAPE_BOX doesn't work
        //UIManager.put("JideTabbedPane.defaultTabShape",JideTabbedPane.SHAPE_WINDOWS);
        FlatIntelliJLaf.install();

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainDialog dialog = new MainDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private com.jidesoft.swing.JideTabbedPane tabMain;
}
```
Error:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.jidesoft.plaf.basic.BasicJideTabbedPaneUI.installColorTheme(BasicJideTabbedPaneUI.java:333)
	at com.jidesoft.plaf.basic.BasicJideTabbedPaneUI.installUI(BasicJideTabbedPaneUI.java:286)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JTabbedPane.setUI(JTabbedPane.java:231)
	at com.jidesoft.swing.JideTabbedPane.setUI(JideTabbedPane.java:318)
	at com.jidesoft.swing.JideTabbedPane.updateUI(JideTabbedPane.java:331)
	at javax.swing.JTabbedPane.<init>(JTabbedPane.java:206)
	at com.jidesoft.swing.JideTabbedPane.<init>(JideTabbedPane.java:292)
	at com.jidesoft.swing.JideTabbedPane.<init>(JideTabbedPane.java:264)
	at debug.jideflat.MainDialog.initComponents(MainDialog.java:28)
```

With dependencies:
```
        <!--flatflaf-->
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf</artifactId>
            <version>0.46</version>
        </dependency>
        <!--flatflaf support for JideSoft-->
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf-jide-oss</artifactId>
            <version>0.46</version>
        </dependency>
        <dependency> 
            <groupId>com.jidesoft</groupId> 
            <artifactId>jide-oss</artifactId> 
            <version>3.6.18</version>
        </dependency> 

```

**Comment by DevCharly** [comment] 2020-12-29 23:30
Thx for reporting.

The problem is that the Jide extensions are not installed
because method `LookAndFeelFactory.installJideExtension()` was not invoked.

Actually I thought that it is required to invoke this method in own `main()` when using Jide components,
but when using other Lafs (tested Windows Laf and Nimbus),
`installJideExtension()` is invoked automatically from `JideTabbedPane.updateUI()`.

So I have to check why it is not invoked for FlatLaf.

For now, invoke `LookAndFeelFactory.installJideExtension()` after `FlatIntelliJLaf.install()` and it works.

BTW if FlatLaf is the only Laf in your app, I would recommend to use [FlatTabbedPane](https://www.javadoc.io/doc/com.formdev/flatlaf-extras/latest/com/formdev/flatlaf/extras/components/FlatTabbedPane.html) instead.
See https://github.com/JFormDesigner/FlatLaf/releases/tag/0.44

**Comment by lgvr123** [comment] 2020-12-29 23:38
Thanks. It is working nice. I'll have a look at the FlatTabbedPane too.

**Comment by DevCharly** [comment] 2021-01-03 11:03
Fixed in main branch.

With next FlatLaf version it is no longer required to invoke `LookAndFeelFactory.installJideExtension()`.

**Closed by DevCharly** 2021-01-03 11:03 UTC
