### ISSUE TITLE
JSpinner - Left border issue

### ISSUE THREAD

**Issue by mlaggner** [JFormDesigner/FlatLaf#382] opened 2021-09-08 19:49 UTC
I've noticed a small glitch in the left border of the JSpinner if you have rounded corners:

![image](https://user-images.githubusercontent.com/1523778/132575550-952044e7-e040-4087-9c75-8fa513ef7623.png)

looks like this could be a regression from https://github.com/JFormDesigner/FlatLaf/commit/3e14f28dc26ec89cc270d1455eb5daebb3daeb96

I've done _no_ direct modifications to the JSpinner LaF (everything done with the .property files and all values for the spinner are the same as in the FlatLaf repo), so I guess this is an issue from FlatLaf

**Comment by DevCharly** [comment] 2021-09-08 21:45
Looks like the embedded text field is **opaque**.

For me it works even with round border:

![image](https://user-images.githubusercontent.com/5604048/132589322-47076f76-4fe1-413c-b9c5-af87320011a3.png)

Do you use a custom editor in the spinner?

You could use [FlatLaf UI Inspector](https://github.com/JFormDesigner/FlatLaf/tree/main/flatlaf-extras#ui-inspector) to check it:

![image](https://user-images.githubusercontent.com/5604048/132589617-81fcdcc7-ab78-4a89-895c-3a3ea0c298be.png)

**Comment by mlaggner** [comment] 2021-09-09 05:03
Thanks for the hint. Looks like this happens when a SpinnerNumberModel is set:

`setModel(new SpinnerNumberModel(calendar.get(Calendar.YEAR), 0, calendar.getMaximum(Calendar.YEAR), 1));`

![image](https://user-images.githubusercontent.com/1523778/132625671-1dc6105a-5567-4cd9-8474-154e1a605a49.png)

If i remove the SpinnerNumberModel, everything is fine (see the border in the field below FSK)

**Comment by DevCharly** [comment] 2021-09-09 09:02
Many thanks, I can reproduce it. It is a bug in FlatLaf...

**Comment by DevCharly** [comment] 2021-09-13 15:21
Fixed in main branch.

**Closed by DevCharly** 2021-09-13 15:21 UTC

**Comment by mlaggner** [comment] 2021-09-14 16:11
thanks, works as expected!
