### ISSUE TITLE
Scroll bar thumb gets very small and hard to click when content is long

### ISSUE THREAD

**Issue by richard-bio** [JFormDesigner/FlatLaf#131] opened 2020-07-16 21:39 UTC
If the component inside a scrollpane is very big, (e.g. a table with a thousand rows in a viewport 250px high) the thumb in the scrollbar gets down to about 4 pixels long which is very hard to click on. The mac system LaF doesn't go below about 20 pixels which I find much more usable.

**Comment by DevCharly** [comment] 2020-07-16 23:09
4px is definitely too small.

The default minimum thumb size in FlatLaf is 8px, which is OK to click on.

So why is it 4px in your app? Did you change the UI value `ScrollBar.minimumThumbSize` somewhere in your app. E.g. with:
~~~java
UIManager.put( "ScrollBar.minimumThumbSize", new Dimension( 4, 4 ) );
~~~

Could you post a screenshot?

**Comment by Nibby** [comment] 2020-07-27 05:14
@DevCharly  This is what the combo box looks like on a fresh Java swing project. 

Using `ScrollBar.minimumThumbSize` with value `new Dimension(4, 8)` results in the following. 
<img width="135" alt="Screen Shot 2020-07-27 at 5 14 30 PM" src="https://user-images.githubusercontent.com/1026658/88505831-a4c90f80-d02c-11ea-9659-bc8797f4aee8.png">
I think this is too small to click on.

Setting the thumb height to 4px makes it invisible:
<img width="134" alt="Screen Shot 2020-07-27 at 5 13 04 PM" src="https://user-images.githubusercontent.com/1026658/88505750-71868080-d02c-11ea-9b4a-ee1075ffa62f.png">

Perhaps Richard is referring to the fact that the default 8px height being too small.

**Comment by DevCharly** [comment] 2020-07-27 12:05
@Nibby thanks for the update.

Now I understand why I was not able to reproduce the issue. I've tried on Windows, which does not have empty space around the thumb because it uses different styling.

On macOS and Linux there is a 2px empty space around the thumb, which is included in the minimum thumb size of 8px. So the visual thumb size became only 4px.

This minimum thumb size of native maxOS scrollbars is also much larger (18px).

Working on a fix...

**Comment by DevCharly** [comment] 2020-07-27 12:44
Now fixed in master branch. New minimum (visible) thumb size is 18px on macOS and Linux and 10px on Windows.

**Closed** 2020-07-29 14:24 UTC
