### ISSUE TITLE
Maximized window showes superfluous pixel-line

### ISSUE THREAD

**Issue by ACRONYM4** [JFormDesigner/FlatLaf#296] opened 2021-03-31 16:44 UTC
![javaw_fvIhoYQax8](https://user-images.githubusercontent.com/61539960/113180099-a2b8ef80-9250-11eb-883c-fb2ab1456ff6.png)

OS: Win10

**Comment by ACRONYM4** [comment] 2021-03-31 16:53
1.1.1

**Comment by Bios-Marcel** [comment] 2021-03-31 16:55
Which JDK (Version and vendor) are you running and which theme exactly are you using?

It's always useful to give such information right of the batch, you'll save the developer some time :)

**Comment by ACRONYM4** [comment] 2021-03-31 16:59
14.0.1 Oracle

**Comment by ACRONYM4** [comment] 2021-03-31 17:01
Also happens on JRE 1.8.0_281.

**Comment by DevCharly** [comment] 2021-03-31 17:48
And if the window is not maximized, you have a green border on all 4 sides of the window, right?

**Comment by ACRONYM4** [comment] 2021-03-31 17:49
Yes.

**Comment by DevCharly** [comment] 2021-03-31 17:56
Thx, can reproduce it. It is a bug.

The reason is that the top window border is painted by FlatLaf (and not by Windows 10).
Simply forgot to hide that top border when window is maximized...

It only stands out when using a colored border...

**Comment by DevCharly** [comment] 2021-03-31 22:25
Fixed in main branch.
https://github.com/JFormDesigner/FlatLaf#snapshots

**Closed by DevCharly** 2021-03-31 22:25 UTC
