### ISSUE TITLE
Illegal Reflective Access when using JFileChooser

### ISSUE THREAD

**Issue by EduardoFSilva** [JFormDesigner/FlatLaf#835] opened 2024-04-24 12:00 UTC
When using JFileChooser, Java 11 complains about a "Illegal Reflective Access" by the class `com.formdev.flatlaf.ui.JavaCompatibility2` on FlatLaf version `3.4.1`

Log:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.formdev.flatlaf.ui.JavaCompatibility2 (file:/C:/Users/Usuario/.m2/repository/com/formdev/flatlaf/3.4.1/flatlaf-3.4.1.jar) to method sun.awt.shell.ShellFolder.get(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.formdev.flatlaf.ui.JavaCompatibility2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by DevCharly** [comment] 2024-04-24 12:56
This is expected behavior for Java 9 to 16, because FlatLaf uses private Java API for those Java versions to get shortcut folders and large icons. There is no public API available in those Java versions.

Since Java 17, public API is available and used.
No warning is shown when using Java 17+.

(duplicate of #694)

**Closed by DevCharly** 2024-04-24 12:56 UTC
